### ISSUE TITLE
Encountering Server Error After Saving `Snippet` with `JavaScript` Code for Dynamic Year Concatenation in Tags Section

### ISSUE THREAD

**Issue by FilipWozniak** [cjkpl/wagtail-cjkcms#10]
I use `<script>document.write(new Date().getFullYear())</script>` code in the footer to dynamically retrieve the current year. I intended to achieve the same functionality, but within the tag section concatenating the `GFN` word with the current year and generate it dynamically. However, when attempting to save the snippet, I encounter a server error.

![image](https://github.com/cjkpl/wagtail-cjkcms/assets/64541581/3a906dba-d4ce-4106-a427-892ad3d7b9db)

![image](https://github.com/cjkpl/wagtail-cjkcms/assets/64541581/883cd7be-65aa-4759-bcf0-132e986d359c)

<img width="741" alt="image" src="https://github.com/cjkpl/wagtail-cjkcms/assets/64541581/74b109d2-22ec-4570-973c-1f592b6fd9c2">

**Comment by cjkpl** [comment]
The issue is not caused by the CMS, but instead by the MyDevil Web Application Firewall. The default level (Level 1) causes this crash. Switching the firewall level to "Disabled" allows saving the snippet.
