### ISSUE TITLE
Add `Countdown` Block to `CMS`

### ISSUE THREAD

**Issue by FilipWozniak** [cjkpl/wagtail-cjkcms#15]
Could you add the `Countdown` block to the `CMS` blocks? It would be useful not only for the `GFN` website but also for others.

https://github.com/ic-thr/dj-gfn/blob/main/home/templates/home/blocks/countdown.html

Perhaps, while at it, we could enhance its appearance using the [`MDB`](https://mdbootstrap.com/docs/standard/plugins/countdown) component? I would be happy to handle the styling if needed.

<img width="755" alt="image" src="https://github.com/user-attachments/assets/4a1cea4b-b854-4a01-8a20-2cdfa93a03d8">

https://mdbootstrap.com/docs/standard/plugins/countdown

<img width="1064" alt="image" src="https://github.com/user-attachments/assets/a4861cfd-c92b-42f0-80d6-4e4084a2ac02">

**Comment by cjkpl** [comment]
Added new "countdown" content block. It uses external library, and has several themes built-in but the HTML styling can be further customised - see the docs for the original library here: https://vincentloy.github.io/simplyCountdown.js/
