### ISSUE TITLE
Add `Pricing` Block to `CMS`

### ISSUE THREAD

**Issue by FilipWozniak** [cjkpl/wagtail-cjkcms#16]
Could we consider adding a [`Pricing` block](https://mdbootstrap.com/docs/standard/extended/bootstrap-comparison-table/) to the `CMS`? The current version feels a bit too.. minimalist 😉 

<img width="1497" alt="image" src="https://github.com/user-attachments/assets/11cd6e46-ec53-476d-9d13-9b7b6bc26507">

**Comment by cjkpl** [comment]
While no new templates were added, I have updated the default ```pricelistitem_block.html``` templates to respect classes in "advanced settings" - allowing limited customisation (```pricelist_block.html``` also respects clases in "advanced settings"). I have also fixed a problem with pricelist items visibility in dark theme.

Screenshot below shows pricelist items decorated using simple classes: ```note note-primary my-1```
![image](https://github.com/user-attachments/assets/1d12fc71-bb2b-48dc-9508-ab2c6572f481)

Furthermore, each site can easily override default price list theme by modifying these two template files:
```templates/cjkcms/blocks/pricelist_block.html```
```templates/cjkcms/blocks/pricelistitem_block```

Changes have been implemented in v. 24.12.3
