### ISSUE TITLE
Remove Deprecated Menu Item Visibility Management System

### ISSUE THREAD

**Issue by FilipWozniak** [cjkpl/wagtail-cjkcms#18]
Can the deprecated menu item visibility management system be removed from the `CMS` now?

<img width="557" alt="image" src="https://github.com/user-attachments/assets/4924a1fc-5cb5-436c-8d5f-e87b5e952533">

**Comment by cjkpl** [comment]
CMS blocks are JSON-based, and ignored in migrations, so If we removed the field in block defintion, this would not cause the data in database disappear. As a result we might have blocks in various websites which are strangely invisible to users, even if nothing is set in the visible block definition. So for safety, a new setting has been added: CJKCMS_NAVBAR_SHOW_VISIBLE_FOR = False. Switch it to True to restore visibility of that block component, if you have problems with any websites.

Changed in v24.12.4
