### ISSUE TITLE
Search System Crashes (on the GFN Website)

### ISSUE THREAD

**Issue by FilipWozniak** [cjkpl/wagtail-cjkcms#2]
Search system crashes (at least on the GFN website), so it is now hidden in top menu. I don't think that this issue occurs if you install `wagtail-cjkcms` from scratch.

<img width="1329" alt="image" src="https://user-images.githubusercontent.com/64541581/224273834-bbc8d9fa-aec7-4fcc-b281-a87a1e7918ef.png">

**Comment by cjkpl** [comment]
Thanks for spotting @FilipWozniak , and thanks for solution @LilJack118 . This issue is caused by lack of pg_trgm extension in Postgres. Install it and search will work again.
