### ISSUE TITLE
Add Functionality That Support Apple Icons

### ISSUE THREAD

**Issue by FilipWozniak** [cjkpl/wagtail-cjkcms#4]
I defined the `Favicon` in the administration panel of `Wagtail`, but the `Page Not Found Redirects` section from [`wagtail-cjk404`](https://github.com/cjkpl/wagtail-cjk404) report an absence of Apple icons.

![image](https://user-images.githubusercontent.com/64541581/227163122-72f9b630-e909-4f83-8da7-8f70ff340272.png)

@cjkpl, I am not sure if it is an error or if I need to define these icons individually somewhere. If it is neither of these, maybe you could add such functionality to the [`wagtail-cjkcms`](https://github.com/cjkpl/wagtail-cjkcms), because I remember that [`dj-gsthr`](https://github.com/cjkpl/dj-gsthr) website also had this problem.

![image](https://user-images.githubusercontent.com/64541581/227164910-cc62dc13-2fc3-4802-85b9-bdb783cc62d4.png)

**Comment by cjkpl** [comment]
Apple icons are supported - via <link href=""" rel="apple-touch-icon" sizes="..."/>

This does not stop some devices / browsers / etc to ignore what is defined in the link, and expect that the icon is actually a PNG file accessible at "/apple-touch-icon.png". I don't think we should care for these non-standard calls.
