### ISSUE TITLE
Highlight Menu Items

### ISSUE THREAD

**Issue by FilipWozniak** [cjkpl/wagtail-cjkcms#5]
I am on the `Programme` subpage, but the `Programme` menu item is not highlighted.

<img width="1331" alt="image" src="https://user-images.githubusercontent.com/64541581/227324217-824c397f-9958-4921-9573-9e1a73e7c788.png">

**Comment by cjkpl** [comment]
In my opinion this is not a problem with cjkcms, but instead with some styling applied to this particular website via frontend/webpack formatting. Re-setting to default light or dark styling reveals correct higlights. Please resolve by fixing styling in specific project.
