### ISSUE TITLE
Introduce Card Image Redirect to `URL`

### ISSUE THREAD

**Issue by FilipWozniak** [cjkpl/wagtail-cjkcms#9]
Add a feature to the `CMS` that will redirect to the specified `URL` upon clicking on the card image. At this moment, button need to be added for this purpose.

<img width="1660" alt="image" src="https://github.com/cjkpl/wagtail-cjkcms/assets/64541581/373e80e6-4f65-4173-9657-bc795460374f">

**Comment by cjkpl** [comment]
Added in 24.5.1:
Support for stretched-link in any Button Link, including in any card. To achieve a stretched link, add "stretched-link" to custom css classes in button's advanced settings. To achieve an invisible button link (e.g. image link), add "stretched-link zero-sized" to custom css of the button.
